### ISSUE TITLE
Patient counting with identical survival time

### ISSUE THREAD

**Issue by bbjiang** [aebergl/MatSurv#10]
Dear aebergl,

Thank you for developing such a handy tool in Matlab platform!

I recently found an issue in using MatSurv: when there are patients having identical survival time, MatSurv may miscount the percentage (i.e., survival probability, the y-axis in the kmplot) and yields wrong plot. And the issue is resolved by adding a tiny random number into the survival time of each patient, i.e., 24 month + 0.002 month. Could you kindly check out whether it is a bug or maybe I did not use MatSurv correctly? For reproducing the issue, I paste my code and my data as below.

Input Data
[input_surv_table.txt](https://github.com/aebergl/MatSurv/files/4532628/input_surv_table.txt)

Code
`V = readtable('input_surv_table.txt');`
`p1 = MatSurv(V.time, V.status, V.group,'norisktable',true,'Print',false);`
`p2 = MatSurv(V.time_with_random, V.status, V.group,'norisktable',true,'Print',false);`

Output Figure
<img width="973" alt="output" src="https://user-images.githubusercontent.com/23666280/80275371-58132700-8713-11ea-8074-48fa22c9ae41.png">

Look forward to your reply and thank you again!

**Comment by aebergl** [comment]
Hello bbjiang
Thanks for your nice comment, for finding this issue and finally for providing a example! Makes my life much easier!
I think I have located the issue.
First try:
`p1 = MatSurv([V.time; V.time_with_random], [V.status; V.status], [V.group; strcat(V.group,'+rand')],'norisktable',true,'Print',false);`

and then:

`p2 = MatSurv([V.time(3:end); V.time_with_random(3:end)], [V.status(3:end); V.status(3:end)], [V.group(3:end); strcat(V.group(3:end),'+rand')],'norisktable',true,'Print',false);`

This clearly indicates that the issue is that I somehow do not count the two censored points at time zero and this messes up the percentage.

Will fix and provide an updated version shortly.

Cheers,


/Anders

**Comment by aebergl** [comment]
This bug has now been fixed. Only affected cases with censored samples with t=0
